= Eddie Corrigall
:published_at: 2015-11-23
:hp-tags: resume, university of waterloo, computer science, bachelor, eddie corrigall

NOTE: Last updated on *{docdate}*

== Summary
I graduated from the University of Waterloo in 2014 with Honours Bachelor of Computer Science (BCS).

I've learned a lot about the Ad Tech Industry this year while working at Eyereturn Marketing Inc. I used Apache Hadoop to operate on and house a lot of data and aggregate the important info into SQL servers for applications.

Now I'm looking to be part of a team, have a well defined role, and ownership over a product or service. My long-term goal is to focus on more traditional software development that will include a release cycle and teamwork.

=== What I’ve worked on in the past

* Mining big data using Apache Hadoop and Apache PigLatin
Data analytics using Python Pandas, NumPy, SciKit Learn
* Real-time analytic software using C# WPF
* Crowd sourcing application using Amazon Web Services (AWS) Mechanical Turk
* Custom implementation of I2C and LPC in C for an Embedded security platform
* Web portal written in SQL, PHP, JavaScript for team knowledge tracking application

=== Side Projects

I have many side projects, some of which are farther along than others. These projects get me involved in technologies to strengthen my abilities and satisfy my ambition for knowledge. If you check out my GitHub account, there are plenty of working examples of my development abilities, so I encourage you to explore!

=== What I'm looking to do next

My internships at the University of Waterloo allowed me to pursue development opportunities within many unique industries. I need to now focus my energy on a career path that will utilize my computer science background and provide me with desirable experience. I want to get involved with big projects with an experienced team leader. I have a strong desire to work with a mobile, backend or frontend team to deliver quality products and services to happy customers.

== CONTACT
1-226-606-2477 +
Yonge and Eglinton, Toronto, ON +
mailto:eddiecorrigall@alumni.uwaterloo.ca[] +
https://linkedin.com/in/eddiecorrigall[@ *LinkedIn*],
https://github.com/eddiecorrigall[@ *GitHub*] +

== SKILLS

[align="center",cols="3",width="90%",options="header"]
|====
|[big]#*Development*#|[big]#*Language*#|[big]#*Framework*#
|Big Data|PigLatin, SQL|Apache Hadoop, CSVKit
|Machine Learning|Python, MATLAB|MatplotLib, NumPy, Pandas, OpenCV, SciKit Learn, HIPS Spearmint
|Web|JavaScript EC5|jQuery, NodeJS, ExpressJS, PassportJS
|Mobile|Java|Android SDK, OpenGL
|Testing|Java, JavaScript EC5|Jasmine, JUnit
|====

== EDUCATION
September 2008 -- May 2014 +
Waterloo, Ontario +
University of Waterloo +

*Honours Bachelor of Computer Science with Co-op*

=== Coursera.org Courses

==== Complete ====
* Programming Mobile Applications for Android Handheld Systems: Part 1
* Programming Mobile Applications for Android Handheld Systems: Part 2
* The Data Scientist's Toolbox
* R Programming

==== In Progress ====
* Programming Mobile Services for Android Handheld Systems: Communication

=== Udemy.com Courses

==== In Progress ====
* JavaScript: Understanding the Wierd Parts
* Learn and Understand NodeJS
* Learn and Understand AngularJS
* Build Web Apps with React JS and Flux

== PROFESSIONAL EXPERIENCE

=== Data Scientist
February 2015 -- September 2015 +
Toronto, Ontario +
EyeReturn Marketing +

*Environment:* Hadoop, Pig Latin, Jython, HIVE, MySQL, MS SQL, JIRA, Confluence, Pentaho, BIRT

* Wrote Hadoop Pig Latin processors as part of anti-fraud efforts
* Took initiative to design and implement more efficient data science mining tools
* Managed ad campaigns, increased performance metrics and wrote final reports for clients

=== Database Analyst
April 2014 -- August 2014 +
Kitchener, Ontario +
AIRO Health +

*Environment:* Python, NumPy, Matplotlib, Pandas, HDF5, SciKit Learn, HIPS Spearmint, MIT StarCluster, Amazon Web Services EC2, Linux

* Set foundation for all future development and machine learning by defining new database structures with HDF5 and utilizing Python library Pandas for large scale vector operations

* Worked with team to design robust heartbeat detector for the purpose of localizing high-quality beat intervals, cleaning signal and supporting graph analytics

* Wrote Matplotlib graph analytic tools to gain insight into optical signals

* Extracted and designed feature sets from heart signals to model macronutrient and caloric intake

=== Software Developer
May 2012 -- December 2012 +
Waterloo, Ontario +
ON Semiconductors +

*Environment:* C# .NET, Visual C#, Microsoft Visual Studios, Window Presentation Foundation, Eclipse, MATLAB, Amazon Web Services: EC2, Mechanical Turk

* Collaborated with software development team to meet product deadlines

* Enabled field engineers to customize and configure ON Semiconductors real-time embedded platform technology

* Instigated solution to reduce cost of certifying company algorithms using Amazon Mechanical Turk

* Developed technical specifications for system development and implemented tools to measure quality of crowd source data using Principal Component Analysis

=== Embedded Software Engineer
September 2011 -- December 2011 +
Shelton, Connecticut, USA +
Pitney Bowes +

*Environment:* Eclipse, C / C++, Interrupt Service Routine, GPIO, LPC bus, I2C bus, Linux

* Developed prototype facilitating core cryptographic products with guidence from MIT electrical engineers

* Utilized interrupt service routine and non-blocking functions in the development of a finite state machine (FSM) written in C to drive Low-Pin Count (LPC) bus over GPIO

* Validated product reliability with test data to safeguard architecture and evaluate performance and reliability of systems implemented

* Carried out the design and development of secure message level protocol utilizing newly implemented LPC driver for application-to-application communication between co-processors

=== Web Developer
January 2011 -- April 2011 +
Waterloo, Ontario +
The Economical Insurance Group / Economical Insurance +

*Environment:* HTML5, CSS3, JavaScript, jQuery, Java, JUnit, JSP, J2EE, JDBC, Oracle, IBM DB2, IBM WebSEAL, RATIONAL ClearCase

* Worked with small team to rewrite a key application for fire rating and territory management

* Required to match existing application functionality by dissecting J2EE source code and IBM DB2 queries

* Developed new broker service based, on existing software requirements

* Applied test-driven development practices using JUnit

* Practiced full stack development while relieving pressure from the Broker Support Team

* Wrote IBM DB2 transactions to safeguard database from application failure

=== Web Developer
May 2010 -- August 2010 +
Waterloo, Ontario, Canada +
The Economical Insurance Group / Economical Insurance +

*Environment:* PHP, Apache, JavaScript, jQuery UI, AJAX, JSON, HTML5, CSS3, Oracle, IBM DB2, IBM WebSEAL, VBA

* Tasked with development of self-serving portal for employees to log their skill set and track team knowledge, strengths and weaknesses

* Investigated use cases and documented web service requirements to develop application using JavaScript and PHP

* Created database schema, wrote IBM DB2 queries, exposed data through custom JSON API and connected front-end via AJAX

* Supported application using PHP back-end with a JavaScript interface designed using jQuery UI

* Created and optimized content for web service using a variety of graphics and useful file formats to enable ease of access and processing for business leadership

* Conducted tests, quality controls, and implemented secure practises

=== Software Developer
September 2009 – December 2009 +
Guelph, Ontario, Canada +
GeoSign / Moxy Media / TSAVO Media +

Environment: C# .NET, ASP .NET, Log4Net, Microsoft Team Foundation Server, MS SQL Server, SOAP, FogBugz

* Used development expertise to maintain ASP .NET and C# web infrastructure

* Actively participated in bug-fixing tasks with FogBugz ticket tracking and Microsoft Team Foundation Server

* Automated queries to notify finance and server team managers via email about critical changes in databases

* Improved company financial data gathering by converting cross-company transactions to Simple Object Access Protocol (SOAP) jobs