== Edward Corrigall
:hp-tags: resume, university of waterloo, computer science, bachelor, eddie corrigall
:published_at: 2019-03-31
:author: Eddie Corrigall
:doctype: article
:encoding: UTF-8
:lang: en
:theme: resume
:icons: font
:icon-set: af

Yonge & St Clair, Toronto, ON +
mailto:eddiecorrigall@gmail.com[] +
https://linkedin.com/in/eddiecorrigall[@ *LinkedIn*],
https://github.com/eddiecorrigall[@ *GitHub*] +

== Skills
* designing and implementing scalable products and productivity tooling
* deploying, migrating and managing Linux-based infrastructure
* automating using CloudFormation, Docker, Ansible, Python, or shell scripting
* scaling existing applications, performance tuning

[%header,cols=3*]
|===
|
|Proficient
|Familiar

|Development
|Python, Java, Bash
|JavaScipt, HTML/CSS

|Frontend Frameworks
|React, GWT (Google Web Toolkit), Looker
|Android SDK, jQuery, UI Kit, Bootstrap

|Backend Frameworks
|Flask, Spring
|SQLAlchemy, Hibernate

|Tooling
|Docker, Git, Ansible, Vagrant, Packer, IntelliJ
|Alembic, Liquibase

|Infrastructure
|AWS: CloudFormation, Redshift, DynamoDB, Kinesis, EC2
|Postgres, Redis, Memcache
|===

== AWS Certifications
[horizontal]
AWS Certified Developer -- Associate 2018:: PSI Services LLC, License Verification #: 9JZ0Y2GCJME4QRW9
AWS Certified Solutions Architect -- Associated 2019:: Preparing to take exam

== Education
[horizontal]
September 2008 -- April 2014:: Honours Bachelor of Computer Science with Co-op +
University of Waterloo, Waterloo, Ontario

== Professional Experience

7 years work experience as a software engineer.

<<<

=== Software Engineer
August 2017 -- _present_ (2 years 2 months) +
*Acquia*, Toronto, Ontario

*Environment:* Agile, Scrum, Git, Java, Liquibase, Spring, Maven, CloudFormation, EC2, ElastiCache, Redshift, Data Pipelines, RDS, DynamoDB, Looker

* rectified configuration to accomplish zero-downtime deploy of rest api auto-scaling group rolling update
* decoupled monolithic deploy: increase stability and speed for deploy during peak traffic
* resolved database throttling in rest api: identified problem using thread dump, mitigated with short term fix, helped plan and coordinate database migration as long term solution
* led team web frontend refactor to help deliver unified experience across company
* led security initiative to overhaul aws resource access for read-only default, and elevate user access following two-factor authentication
* wrote core product feature: report authoring, to provide customers custom analytics -- delivered on time without issue even with set backs
* improved existing geo-location integration for improved accuracy with no service interruption
* built in-house tooling to improve developer and operation experience for team

=== Platform Engineer
January 2016 -- August 2017 (1 year 8 months) +
*Instacart*, Toronto, Ontario

*Environment:* Python, PyTest, Flask, SQLAlchemy, Alembic, Postgres, Flask, Memcached, Redis, Redis Queue, Supervisor, Ansible, Vagrant, JIRA, SOAP, REST, bash, tmux, vim, git

* implemented rest api ecommerce features
* optimized offers engine and added couponing feature
* on-call technical support for disaster recovery
* providing hot-fix solutions to comply with service-level agreement
* first to assess and troubleshoot issues affecting customer eCommerce experience
* preparation and deployment of new software releases to staging and production environments
* coordinating downtime and hardware upgrades for retailer environments

<<<

=== Data Analyst
February 2015 -- December 2015 (1 year) +
*EyeReturn Marketing*, Toronto, Ontario +

*Environment:* Hadoop, Pig Latin, Jython, HIVE, MySQL, MS SQL, JIRA, Confluence, Pentaho, BIRT

* wrote Hadoop Pig Latin processors as part of anti-fraud effort
* took initiative to design and implement more efficient data science mining tools
* managed ad campaigns, increased performance metrics and wrote final reports for clients

=== Internships

2 years working experience in University of Waterloo co-operative program.

[%header,cols=6*]
|===
| Company
| Location
| Role
| Starting
| Timeframe
| Performance Evaluation

| ON Semiconductors
| Waterloo, Ontario
| Software Developer
| May 2012
| 8 months
| Very Good

| Pitney Bowes
| Shelton, Connecticut, USA
| Embedded Software Engineer
| September 2011
| 4 months
| Excellent

| Economical Insurance
| Waterloo, Ontario
| Web Developer
| January 2011
| 4 months
| Excellent

| Economical Insurance
| Waterloo, Ontario
| Web Developer
| May 2010
| 4 months
| Excellent

| TSAVO Media
| Guelph, Ontario
| Software Developer
| September 2009
| 4 months
| Satisfactory
|===
