:hp-tags: resume, eddie, corrigall, university of waterloo, computer science, bachelor, software, developer, engineer
:published_at: 2021-06-27
:author: Eddie Corrigall
:doctype: article
:encoding: UTF-8
:lang: en
:theme: resume
:icons: font
:icon-set: af
:showtitle: false

= Edward Corrigall

Toronto, Ontario, Canada +
mailto:eddiecorrigall@gmail.com[],
https://linkedin.com/in/eddiecorrigall[@*LinkedIn*],
https://github.com/eddiecorrigall[@*GitHub*]

== Skills
* designing and implementing scalable products and productivity tooling
* planning long term objectives and working with teams to accomplish goals
* scaling existing products, performance tuning application and infrastructure
* automating using CloudFormation, Docker, Ansible, Python, or shell scripting
* deploying, migrating and managing Linux-based systems

[%rotate,cols="4*",frame=none,grid=rows]
|===

|
|★★★★★ (5/5)
|★★★★☆ (4/5)
|★★★☆☆ (3/5)

|*Infrastructure*
|CloudFormation, EC2, ECS, ElasticSearch
|Redshift, DynamoDB, RDS, ElastiCache
|Ansible, Vagrant, Packer, Docker

|*Languages*
|Python, Java, Bash
|JavaScipt
|

|*Backend*
|Flask, SQLAlchemy, Alembic
|Hibernate, Liquibase, Google Web Toolkit
|Android SDK, Spring, ExpressJS

|*Frontend*
|
|ReactJS
|jQuery, UIkit, VueJS, Bootstrap

|*Analytics*
|Looker
|Kinesis, CloudWatch
|

|===

== Professional Experience

* 8+ years work experience as a software engineer.
* 4+ years experience with cloud services.
* certified Amazon Web Service professional.

=== Mark43
*Senior Software Engineer*, July 2020 -- _present_

*Environment:* MySQL, Java, Docker, AWS, Redis, Kafka, ElasticSearch, ReactJS, Looker

* code contributor of record management system team emergency services software
* authored ElasticSearch request for change, describing: risk, mitigation steps, short and long term goals
* reduced ElasticSearch cluster capacity by roughly 40% (2TB+) without deleting any customer facing data
* improved MySQL average query response time by optimizing internal notification service
* overhauled State to Federal report exports to easily maintain code and rapidly on-board new customers

<<<

=== Naborly
*Senior Software Engineer*, December 2019 -- July 2020

*Environment:* Python, NodeJS, ExpressJS, ReactJS, MongoDB, Looker, Heroku, Stitch, Docker, RDS

* led scrum, planning, grooming and retro meetings more effectively
* setup local development for team with docker compose and selenium end-to-end testing
* built out new CloudFormation ECS service stack to migrate cloud providers
* helped build new api for rent guarantee claims service
* secured AWS account with IAM stack groups and policies
* reduced AWS costs from $250 to $40 USD per day -- saving company more than $75,000 USD per year
* improved looker no-SQL to SQL integration with stitch by adding MongoDB indices
* took initiative to overhaul Looker analytics

=== Acquia
*Software Engineer*, August 2017 -- December 2019

*Environment:* Java, Looker, CloudFormation, EC2, ElastiCache, Redshift, Kinesis, Data Pipelines, RDS, DynamoDB, Hibernate, Liquibase, Spring

* automated zero-downtime deploy of rest api auto-scaling group rolling update
* decoupled monolithic deploy: increase stability and speed for deploy during peak traffic
* designed rolled-out company security policy for read-only and elevate user access
* led team web frontend refactor to help deliver unified experience across company
* replaced existing geo-location integration for improved accuracy and $100,000 USD per year in savings
* on-schedule completion of core product: report authoring, providing customers with custom analytics
* resolved outstanding rest api database throttling
* built in-house tooling to improve developer and operation experience for team

=== Instacart
*Platform Engineer*, January 2016 -- August 2017

*Environment:* Python, Flask, SQLAlchemy, Alembic, PostgreSQL, Memcached, Redis, Ansible, Vagrant

* implemented rest api ecommerce features
* optimized offers engine and added couponing feature
* on-call technical support for disaster recovery
* providing hot-fix solutions to comply with service-level agreement
* first to assess and troubleshoot issues affecting customer eCommerce experience
* preparation and deployment of new software releases to staging and production environments
* coordinating downtime and hardware upgrades for retailer environments

<<<

== Education
[horizontal]
Bachelor of Computer Science -- Honours, Co-op :: University of Waterloo +
Waterloo, Ontario

== Certifications
[horizontal]
AWS Certified Developer -- Associate 2018 :: PSI Services LLC +
https://aw.certmetrics.com/amazon/public/verification.aspx[License Verification #9JZ0Y2GCJME4QRW9]

[horizontal]
Programming Mobile Services for Android Handheld Systems -- Comunication 2016 :: Corsera Course Certificates +
https://www.coursera.org/account/accomplishments/verify/MEAJXDNAXQ[Credential ID MEAJXDNAXQ]

[horizontal]
Programming Mobile Services for Android Handheld Systems -- Part 2, 2015 :: Corsera Course Certificates +
https://www.coursera.org/account/accomplishments/verify/ANB9AQDUBZ[Credential ID ANB9AQDUBZ]

[horizontal]
Programming Mobile Services for Android Handheld Systems -- Part 1, 2015 :: Corsera Course Certificates +
https://www.coursera.org/account/accomplishments/verify/R5JF2BGZTM[Credential ID R5JF2BGZTM]
