:hp-tags: resume, eddie, edward, corrigall, university of waterloo, computer science, bachelor, software, developer, engineer, devops
:published_at: 2023-10-01
:author: Eddie Corrigall
:doctype: article
:encoding: UTF-8
:lang: en
:theme: resume
:icons: font
:icon-set: af
:showtitle: false

= Edward Corrigall

Kitchener, Ontario, Canada +
mailto:eddiecorrigall@gmail.com[],
https://linkedin.com/in/eddiecorrigall[@*LinkedIn*],
https://github.com/eddiecorrigall[@*GitHub*]

== Skills
* designing and implementing scalable products and productivity tooling
* planning long term objectives and working with teams to accomplish goals
* scaling existing products, performance tuning application and infrastructure
* automating using CloudFormation, Docker, Ansible, Python, or shell scripting
* deploying, migrating and managing enterprise software
* onboarding, mentoring, documenting and presenting
* focusing on simple and effective solutions

[%rotate,cols="4*",frame=none,grid=rows]
|===

|
|★★★★★ (5/5)
|★★★★☆ (4/5)
|★★★☆☆ (3/5)

|*Infrastructure*
|CloudFormation, EC2, ECS, VPC
|Redshift, S3, DynamoDB, RDS, ElastiCache, Docker, Packer, ElasticSearch
|Ansible, Vagrant, Kubernetes, Helm

|*Languages*
|Python, Java, Bash
|JavaScript, TypeScript
|

|*Backend*
|Flask, SQLAlchemy, Alembic, ExpressJS
|Hibernate, Liquibase, Google Web Toolkit
|Android SDK, Spring, ExpressJS

|*Frontend*
|
|ReactJS
|jQuery, UIkit, VueJS, Bootstrap

|*Analytics*
|Looker
|Kinesis, CloudWatch
|

|===

== Professional Experience

* Certified Amazon Web Service professional
* 10+ years software as a service (SaaS) experience
    - Development experience and automation
    - Software Development
    - Infrastructure Development
    - CI/CD Development
    - Data warehousing and Data Integrations
* 7+ years cloud service experience
    - Amazon Web Services,
    - Google Cloud Platform, and
    - Heroku

<<<

=== https://ledn.io/[Ledn]
*Senior DevOps Engineer*, October 2022 -- April 2023

*Business:* financial tech focused on lending and savings account for digital assets

*Environment:* MongoDB, Mongoose, NodeJS, TypeScript, Docker, AWS Lambda, Serverless, Webpack, GitHub Actions, AWS, MongoDB Atlas

* focused on increasing developer velocity and information security
* automated rollout of internal password management tool (Passbolt) using Packer, Cloudformation, Elastic Load Balancer, AutoScaling Group and Route53
* created new one-way file upload service to secure sensitive customer data with Cloudformation and S3
* refactored out critical vulnerabilities out of NodeJS project
* incorporated NodeJS Package Module audit into CI/CD builds
* automated iOS TestFlight release to Apple Store using Fastlane and GitHub Actions
* investigated and solved single-lambda deployment failure relating to Webpack dependency traversal
* investigated and mitigated database migration release issues
* participated in long-term support planning and upgrades for NodeJS, MongoDB, CloudFormation Stack Resource Limit
* unblocked engineering release process by splitting large AWS Cloudformation Stack managed by Serverless infrastructure tool
* migrated frontend team CI/CD to a GitHub Actions Gitflow from CircleCI for improved workflow and cost savings

=== https://clear.co/[Clearco]
*Senior Software Engineer*, August 2021 -- October 2022

*Business:* business-to-business financial services: merchant cash advance, revenue sharing

*Environment:* PostgreSQL, TypeScript, Docker, Helm, Lens, GCP Kubernetes, GCP SQL, Netlify, VueJS, pgmigrate, Looker, Jenkins, GitHub Actions, JMeter, Figma

* backend technical lead for greenlit bills service product to support founder merchant cash advance
* bootstrapped NodeJS backend API project for engineers with team specific CI/CD workflow
* enabled team to experiment in isolation from monolith codebase to rapidly deploy changes for the first time
* completed migration from monolith to micro-service: codebase, source control, database and software release pipeline
* tail-blazed path for engineering organization to break out into micro-services by offering support with documentation, knowledge share session and playbook
* protected customers from peek traffic by building out performance + load test automation
* prevented degraded experience during Black Friday and Cyber Monday for eCommerce customers for the first time

<<<

=== https://mark43.com/[Mark43]
*Senior Software Engineer*, July 2020 -- August 2021

*Business:* emergency service (police, fire, and paramedic) software as a service

*Environment:* MySQL, Java, Docker, AWS, Redis, Kafka, ElasticSearch, ReactJS, Looker

* code contributor of record management system team emergency services software
* overhauled State to Federal report export software for developers to easily maintain code and rapidly on-board new customers
* authored ElasticSearch request for change, describing: risk, mitigation steps, short and long term goals
* reduced ElasticSearch cluster capacity by roughly 40% (2TB+) without deleting any customer facing data
* improved MySQL average query response time by optimizing customer facing notification system

=== https://www.naborly.com/[Naborly]
*Senior Software Engineer*, December 2019 -- July 2020

*Business:* Tenant and landlord services

*Environment:* Python, NodeJS, ExpressJS, ReactJS, MongoDB, Looker, Heroku, Stitch, Docker, RDS

* led on scrum, planning, grooming and retro meetings
* setup local development for team with docker compose and selenium end-to-end testing
* built out new CloudFormation ECS service stack to migrate cloud providers from Heroku to AWS
* delivered new API for rent guarantee claims service
* secured AWS account with IAM stack groups and policies
* reduced AWS costs from $250 to $40 USD per day -- saving company more than $75,000 USD per year
* improved looker no-SQL to SQL integration with stitch by adding MongoDB indices
* assumed ownership over Looker analytics to support and train sales / marketing teams
* transformed Looker analytics into a self-serve internal product

<<<

=== https://www.acquia.com/[Acquia]
*Software Engineer*, August 2017 -- December 2019

*Business:* drupal hosting / content-management system software as a service

*Environment:* Java, Looker, CloudFormation, EC2, ElastiCache, Redshift, Kinesis, Data Pipelines, RDS, DynamoDB, Hibernate, Liquibase, Spring

* automated zero-downtime deploy of RESTful API auto-scaling group rolling update
* decoupled monolithic deploy: increase stability and speed for deploy during peak traffic
* rolled-out company security policy for read-only and elevate user access using Simple Token Service and IAM Roles
* led team web frontend refactor to help deliver unified experience across company
* retrofitted existing geo-location integration for improved accuracy and $100,000 USD per year in savings
* on-schedule completion of core product: report authoring, providing customers with custom analytics dashboards for web traffic analysis
* built in-house tooling to improve developer and operation experience for team for SSH autocomplete and AWS Session Tokens to assume roles
* resolved outstanding RESTful API database throttling

=== https://www.instacart.ca/[Unata / Acquired by Instacart]
*Platform Engineer*, January 2016 -- August 2017

*Business:* grocery eCommerce and shopping fulfillment

*Environment:* Python, Flask, SQLAlchemy, Alembic, PostgreSQL, Memcached, Redis, Ansible, Vagrant

* implemented RESTful API eCommerce features including coupon clipping and up-sell at checkout
* optimized offers engine and added couponing feature
* on-call technical support for disaster recovery
* providing hot-fix solutions to comply with service-level agreement
* first to assess and troubleshoot issues affecting customer eCommerce experience
* preparation and deployment of new software releases to staging and production environments
* coordinating downtime and hardware upgrades for retailer environments
* solved outstanding many-to-many mapping issue causing product mismatch for Lowe's Foods customer

<<<

== Education
[horizontal]
Bachelor of Computer Science -- Honours, Co-op :: University of Waterloo +
Waterloo, Ontario

=== HackerRank Certificates
[horizontal]
Java (Basic) Certificate 2023 :: HackerRank +
https://www.hackerrank.com/certificates/717d4639a4d7[Verification #717d4639a4d7]
Python (Basic) Certificate 2023 :: HackerRank +
https://www.hackerrank.com/certificates/726081e81ce7[Verification #726081e81ce7]

=== Amazon Web Services Certificates
[horizontal]
AWS Certified Developer -- Associate 2018 :: PSI Services LLC +
https://aw.certmetrics.com/amazon/public/verification.aspx[License Verification #9JZ0Y2GCJME4QRW9]

=== University of Maryland, College Park
[horizontal]
Programming Mobile Services for Android Handheld Systems -- Part 1, 2015 :: Coursera +
https://www.coursera.org/account/accomplishments/verify/R5JF2BGZTM[Verification #R5JF2BGZTM]
Programming Mobile Services for Android Handheld Systems -- Part 2, 2015 :: Coursera +
https://www.coursera.org/account/accomplishments/verify/ANB9AQDUBZ[Verification #ANB9AQDUBZ]
Programming Mobile Services for Android Handheld Systems -- Communication, 2016 :: Coursera +
https://www.coursera.org/account/accomplishments/verify/MEAJXDNAXQ[Verification #MEAJXDNAXQ]

== Tech Project Highlights
* https://github.com/eddiecorrigall/elang[Toy Programming Language]
* https://github.com/dtjohnson/xlsx-populate[Microsoft Excel API for NodeJS]
* https://github.com/eddiecorrigall/tinyurl[Tiny URL Service]
* https://github.com/eddiecorrigall/GraphicsEngine[OpenGL Game Engine]
* https://github.com/eddiecorrigall/database-revisions[Agnostic Database Migration Tool]

== Hobbies and Interests
* Outdoors: gardening, koi pond, astronomy
* Computers: home networking (FreeNAS), retro computers, compilers
* Sports: rock climbing, sailing
* Other: music (bass, guitar, etc.), home brew (beer, wine, mead, etc.)
